permalink:        pretty
relative_permalinks: true

highlighter: pygments
timezone: America/Chicago
paginate: 3

title: Chuck Housley
description: "Just a guy, building a blog. Nothing to see here yet"

author:
  name: 'Chuck Housley'
  url: 'charleshousley.com'

gems:
  - jekyll-redirect-from