permalink:        pretty

highlighter: rouge
timezone: America/Chicago
paginate: 3

title: Chuck Housley
description: "charles@charleshousley.com"

author:
  name: 'Chuck Housley'
  url: 'charleshousley.com'

pages_list:
  Resume(updated March 2016): '/resume/'
  top10dogs.com: 'http://top10dogs.com'
  
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-coffeescript

