permalink:        pretty
relative_permalinks: true

highlighter: pygments
timezone: America/Chicago
paginate: 3

title: Chuck Housley
description: "charles@charleshousley.com"

author:
  name: 'Chuck Housley'
  url: 'charleshousley.com'

pages_list:
  Resume: '/resume/'
  
gems:
  - jekyll-redirect-from